#sapi-request

price:
  host: "poc-eapi-products-5qguky.5sc6y6-3.usa-e2.cloudhub.io"
  path: "/api/v1/prices"

  
stock:
  host: "poc-eapi-products-5qguky.5sc6y6-3.usa-e2.cloudhub.io" 
  path: "/api/v1/stock"  
  
customer:
  host: "poc-eapi-products-5qguky.5sc6y6-3.usa-e2.cloudhub.io"
  path: "/api/v1/customer"  
  

tax:
  host: "poc-eapi-products-5qguky.5sc6y6-3.usa-e2.cloudhub.io"
  path: "/api/v1/tax"    
  
orders:
  host: "poc-sapi-orders-soql-5qguky.5sc6y6-3.usa-e2.cloudhub.io"
  path: "/v1/order/create"
    
    
  details:
    host: "poc-sapi-orders-soql-5qguky.5sc6y6-3.usa-e2.cloudhub.io"
    path: "/api/v1/orders/{orderId}"
    
