#%RAML 1.0
title: poc-papi-orders
version: v1
protocols:
  - HTTP
  - HTTPS

traits:
  Client-ID-Policy: !include trait.raml


/v1:
  /order/create:
    post:
      is: [Client-ID-Policy]
      body:
        application/json:
          example: !include example/order-create-request-file.json
      responses:
        200:
          body:
            application/json:
              example: !include example/order-create-response-file.json
                
  /orders/details:
    post:
      is: [Client-ID-Policy]
      body:
        application/json:
          example: !include example/order-detail-request-file.json
      responses:
        200:
          body:
            application/json:
              example: !include example/order-details-response-file.json
                
            
          